version: 2
jobs:
  build-and-test:
    macos:
      xcode: "11.4"
    steps:
      - checkout
      - run:
         name: Install cocoapods
         command: sudo gem install cocoapods -v 1.8.4
      - run:
         name: Install pods
         command: pod install
      - run:
          name: Run Tests
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPhone 8
            SCAN_SCHEME: VGSCollectSDK
jobs:
  carthage-test:
    macos:
      xcode: "11.4"
    steps:
      - checkout
      -run:
        name: Carthage update iOS
        command: cd demoapp/; carthage update --platform iOS
      -run:
        name: Build
        command: cd demoapp/; xcodebuild -project demoapp.xcodeproj -target demoapp -configuration Release

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
  carthage-test:
    job:
      - carthage-test
